# - CMake JUCE Audio Plug-in Code-Signing
#
# This file contains functions to code-sign the plug-ins. 
# ToDo: Add an option to use deep code-signing

# Options for enabling the the code-signing.
option(CJAP_CODESIGN_ENABLED "Enable the plug-in code-signing" OFF)
option(CJAP_CODESIGN_WINDOWS_PACKAGE_ENABLED "Enable the plug-in code-signing" ${CJAP_CODESIGN_ENABLED})

# The variables to sign plug-ins
set(CJAP_CODESIGN_PROJECT_NAME "${CMAKE_PROJECT_NAME}" CACHE STRING "The name of the project")
option(CJAP_CODESIGN_TARGET_ENABLED "Create a global code-signing target instead of target post build commands" ON)
set(CJAP_CODESIGN_WINDOWS_CERT "" CACHE PATH "The Windows (.p12) certificate file")
set(CJAP_CODESIGN_WINDOWS_PASSWORD "" CACHE STRING "The password of the Windows (.p12) certificate files")
set(CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT "Developer ID Application" CACHE STRING "The Apple Developer ID Application certificate")
set(CJAP_CODESIGN_APPLE_DEV_ID_INSTALLER_CERT "Developer ID Installer" CACHE STRING "The Apple Developer ID Installer certificate")
set(CJAP_CODESIGN_APPLE_KEYCHAIN_PROFILE_INSTALLER "notary-installer" CACHE STRING "The Apple keychain profile for installer")
set(CJAP_CODESIGN_PACE_EMAIL "" CACHE STRING "The PACE developer email")
set(CJAP_CODESIGN_PACE_WCGUID "" CACHE STRING "The PACE GUID")
option(CJAP_CODESIGN_PACE_CLOUD_SERVICE "Enable the plug-in cloud code-signing" OFF)
set(CJAP_CODESIGN_PACE_PASSWORD "" CACHE STRING "The PACE Password for the cloud service")
set(CJAP_CODESIGN_TIMESTAMP_SERVER "http://timestamp.sectigo.com" CACHE STRING "The timestamp server to sign packages on Windows")

# Internal
set(CJAP_CODESIGN_BUILD_PATH "${CMAKE_CURRENT_BINARY_DIR}/CJAP_Codesign")
set(CJAP_CODESIGN_WINDOWS_CERT_PFX "${CJAP_CODESIGN_BUILD_PATH}/cert.pfx")

# - Searchs for a valid Apple developer certificate 
#
# The code searchs a valid Apple developer certificate and 
# intializes the signing attributes.
if(CJAP_CODESIGN_ENABLED AND APPLE)
  execute_process(COMMAND security find-certificate -c ${CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT} OUTPUT_VARIABLE CERTIFICATE_RESULT ERROR_VARIABLE CERTIFICATE_ERROR)
  if(CERTIFICATE_RESULT)
    message(STATUS "Apple ${CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT} Certificate is found")
  else()
    message(WARNING "Apple ${CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT} Certificate cannot be found")
    set(CJAP_CODESIGN_ENABLED OFF)
  endif()

  if(CJAP_PACKAGE_ENABLED)
    execute_process(COMMAND security find-certificate -c ${CJAP_CODESIGN_APPLE_DEV_ID_INSTALLER_CERT} OUTPUT_VARIABLE CERTIFICATE_RESULT ERROR_VARIABLE CERTIFICATE_ERROR)
    if(CERTIFICATE_RESULT)
      message(STATUS "Apple ${CJAP_CODESIGN_APPLE_DEV_ID_INSTALLER_CERT} Certificate is found")
    else()
      message(WARNING "Apple ${CJAP_CODESIGN_APPLE_DEV_ID_INSTALLER_CERT} Certificate cannot be found")
      set(CJAP_CODESIGN_ENABLED OFF)
    endif()
  endif()

  set(CMAKE_XCODE_ATTRIBUTE_ENABLE_HARDENED_RUNTIME TRUE CACHE BOOL "")
  set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_INJECT_BASE_ENTITLEMENTS "$<$<CONFIG:Debug>:YES>")
endif()

# - Searchs the wraptool program
#
# The code searchs for wraptool on the system. If the program cannot be
# found and the PACE code-signing variables are defined, the code 
# generates an error. If the Pace cloud-service is enabled, the code searchs
# for iloktool. If the program cannot be found, the code generates an error.
if(CJAP_CODESIGN_ENABLED)
  if(APPLE)
    set(CJAP_CODESIGN_SIGNATOR_FILE_PATH "${CJAP_CODESIGN_BUILD_PATH}/signator.sh")
    if(NOT CJAP_CODESIGN_PACE_EMAIL STREQUAL "" AND NOT CJAP_CODESIGN_PACE_WCGUID STREQUAL "")
      find_program(CJAP_CODESIGN_WRAPTOOL_EXE "wraptool" PATHS "/Applications/PACEAntiPiracy/Eden/Fusion/bin/" "/Applications/PACEAntiPiracy/Eden/Fusion/Current/bin/" REQUIRED)
      message(STATUS "AAX Plugins code-signing available ${CJAP_CODESIGN_WRAPTOOL_EXE}")
    endif()

    if(CJAP_CODESIGN_PACE_CLOUD_SERVICE)
      find_program(CJAP_CODESIGN_ILOKTOOL_EXE "iloktool" REQUIRED)
      if(CJAP_CODESIGN_PACE_PASSWORD STREQUAL "")
        message(STATUS "AAX Plugins cloud code-signing ${CJAP_CODESIGN_ILOKTOOL_EXE} - use default password of the keychain")
      else()
        message(STATUS "AAX Plugins cloud code-signing ${CJAP_CODESIGN_ILOKTOOL_EXE}")
      endif()
    endif()

    file(WRITE "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "#!/bin/sh\n\n")
    if(CJAP_CODESIGN_WRAPTOOL_EXE)
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "if [[ \"$1\" == *.aaxplugin* ]]; then\n")
      if(CJAP_CODESIGN_PACE_CLOUD_SERVICE)
        if(CJAP_CODESIGN_PACE_PASSWORD STREQUAL "")
          set(CJAP_CODESIGN_ILOK_ARGS "--account ${CJAP_CODESIGN_PACE_EMAIL} ")
        else()
          set(CJAP_CODESIGN_ILOK_ARGS "--account ${CJAP_CODESIGN_PACE_EMAIL} --password ${CJAP_CODESIGN_PACE_PASSWORD}")
        endif()
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  ILOKTOOL=\"${CJAP_CODESIGN_ILOKTOOL_EXE}\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  WRAPTOOL=\"${CJAP_CODESIGN_WRAPTOOL_EXE}\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  ACCOUNT=\"${CJAP_CODESIGN_PACE_EMAIL}\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  SIGNID=\"${CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT}\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  WCGUID=\"${CJAP_CODESIGN_PACE_WCGUID}\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  if ! $ILOKTOOL cloud --open ${CJAP_CODESIGN_ILOK_ARGS} | grep -q \"Success\"; then\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    echo \"Signing failed for $1 (open session)\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    exit 1\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  fi\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  if $WRAPTOOL sign --verbose --account $ACCOUNT --signid \"$SIGNID\" --wcguid $WCGUID --in \"\$1\" --allowsigningservice | grep -q \"ERROR\"; then\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    echo \"Signing failed for \$1 (signing)\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    exit 1\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  fi\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  $WRAPTOOL verify --in \"\$1\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  if ! $ILOKTOOL cloud --close ${CJAP_CODESIGN_ILOK_ARGS} | grep -q \"Success\"; then\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    echo \"Signing failed for \$1 (close session)\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    exit 1\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  fi\n")
      else()
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  ${CJAP_CODESIGN_WRAPTOOL_EXE} sign --verbose --account ${CJAP_CODESIGN_PACE_EMAIL} --signid \"${CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT}\" --wcguid ${CJAP_CODESIGN_PACE_WCGUID} --in \"\$1\"\n")
      endif()
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "else\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "  codesign --sign \"${CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT}\" --deep -f -o runtime --timestamp -v \"\$1\"\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "fi\n")
    else()
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "codesign --sign \"${CJAP_CODESIGN_APPLE_DEV_ID_APPLICATION_CERT}\" --deep -f -o runtime --timestamp -v \"\$1\"\n")
    endif()
    file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "codesign -dvv \"\$1\"\n")
    file(CHMOD "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)

    if(CJAP_CODESIGN_TARGET_ENABLED)
      set(CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH "${CJAP_CODESIGN_BUILD_PATH}/signator_all.sh")
      file(WRITE "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "#!/bin/sh\n\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "SIGNATOR=\"${CJAP_CODESIGN_SIGNATOR_FILE_PATH}\"\n")
      file(CHMOD "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
      add_custom_target(${CJAP_CODESIGN_PROJECT_NAME}_CodeSign ALL ${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH} $<CONFIG>)
    endif()
  elseif(WIN32)
    file(MAKE_DIRECTORY ${CJAP_CODESIGN_BUILD_PATH})
    set(CJAP_CODESIGN_SIGNATOR_FILE_PATH "${CJAP_CODESIGN_BUILD_PATH}/signator.bat")

    if(NOT CJAP_CODESIGN_PACE_EMAIL STREQUAL "" AND NOT CJAP_CODESIGN_PACE_WCGUID STREQUAL "")
      find_program(CJAP_CODESIGN_WRAPTOOL_EXE "wraptool" PATHS "$ENV{ProgramFiles\(x86\)}/PACEAntiPiracy/Eden/Fusion/Versions/5" REQUIRED)
      message(STATUS "AAX Plugins code-signing available with ${CJAP_CODESIGN_WRAPTOOL_EXE}")
    endif()

    if(CJAP_CODESIGN_PACE_CLOUD_SERVICE)
      find_program(CJAP_CODESIGN_ILOKTOOL_EXE "iloktool" PATHS "$ENV{ProgramFiles\(x86\)}/iLok License Manager" REQUIRED)
      if(CJAP_CODESIGN_PACE_PASSWORD STREQUAL "")
        message(STATUS "AAX Plugins cloud code-signing ${CJAP_CODESIGN_ILOKTOOL_EXE} - use default password of the keychain")
      else()
        message(STATUS "AAX Plugins cloud code-signing ${CJAP_CODESIGN_ILOKTOOL_EXE}")
      endif()
    endif()

    if(CJAP_CODESIGN_WINDOWS_CERT AND CJAP_CODESIGN_WINDOWS_PACKAGE_ENABLED)
      file(COPY_FILE ${CJAP_CODESIGN_WINDOWS_CERT} ${CJAP_CODESIGN_WINDOWS_CERT_PFX})
    endif()

    if(CJAP_CODESIGN_WRAPTOOL_EXE)
      file(WRITE "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "@echo off\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "setlocal\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set WRAPTOOL=\"${CJAP_CODESIGN_WRAPTOOL_EXE}\"\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set ACCOUNT=${CJAP_CODESIGN_PACE_EMAIL}\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set KEYFILE=\"${CJAP_CODESIGN_WINDOWS_CERT}\"\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set KEYPASSWORD=\"${CJAP_CODESIGN_WINDOWS_PASSWORD}\"\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set WCGUID=\"${CJAP_CODESIGN_PACE_WCGUID}\"\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set ILOKTOOL=\"${CJAP_CODESIGN_ILOKTOOL_EXE}\"\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set ILOKPASSWORD=\"${CJAP_CODESIGN_PACE_PASSWORD}\"\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "set AAXFILE=%1\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "\n")
      if(CJAP_CODESIGN_PACE_CLOUD_SERVICE)
        if(CJAP_CODESIGN_PACE_PASSWORD STREQUAL "")
          file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "%ILOKTOOL% cloud --open --account %ACCOUNT% | find /i \"Success\" >nul || (\n")
        else()
          file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "%ILOKTOOL% cloud --open --account %ACCOUNT% --password %ILOKPASSWORD% | find /i \"Success\" >nul || (\n")
        endif()
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    echo Failed to open cloud session.\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    exit /b 1\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" ")\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "echo \"Processing %AAXFILE%\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "%WRAPTOOL% sign --verbose --allowsigningservice --account %ACCOUNT% --keyfile %KEYFILE% --keypassword %KEYPASSWORD% --wcguid %WCGUID% --in %AAXFILE%\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "%ILOKTOOL% cloud --close --account %ACCOUNT% | find /i \"Success\" >nul || (\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    echo Failed to close cloud session.\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "    exit /b 1\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" ")\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "\n")
      else()
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "%WRAPTOOL% sign --account %ACCOUNT% --keyfile \"%KEYFILE%\" --keypassword %KEYPASSWORD% --wcguid %WCGUID% --in %1\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_FILE_PATH}" "\n")
      endif()
    endif()

    if(CJAP_CODESIGN_TARGET_ENABLED)
      set(CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH "${CJAP_CODESIGN_BUILD_PATH}/signator_all.bat")
      file(WRITE "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "@echo off\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "setlocal\n")
      file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "\n")
      add_custom_target(${CJAP_CODESIGN_PROJECT_NAME}_CodeSign  ALL ${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH} $<CONFIG>)
    endif()
  endif()
endif()

# - Gets the output directory of a target
#
# The function returns the output directory
function(target_get_output_path target format targetpath)
  if(TARGET ${target})
    if(APPLE)
      get_target_property(PLUGIN_NAME ${target} JUCE_PLUGIN_NAME)
      get_target_property(PLUGIN_OUTPUT_DIRECTORY ${target} LIBRARY_OUTPUT_DIRECTORY)
      string(REPLACE "$<CONFIG>" "$1" PLUGIN_OUTPUT_DIRECTORY ${PLUGIN_OUTPUT_DIRECTORY})
      get_target_property(PLUGIN_EXTENSION ${target}_${format} BUNDLE_EXTENSION)
      if(NOT PLUGIN_EXTENSION)
        set(PLUGIN_EXTENSION "app")
      endif()
      set(PLUGIN_PATH "${PLUGIN_OUTPUT_DIRECTORY}/${format}/${PLUGIN_NAME}.${PLUGIN_EXTENSION}")
      cmake_path(NATIVE_PATH PLUGIN_PATH NORMALIZE PLUGIN_PATH)
      set(${targetpath} "${PLUGIN_PATH}" PARENT_SCOPE)
    elseif(WIN32)
      get_target_property(PLUGIN_NAME ${target} JUCE_PLUGIN_NAME)
      get_target_property(PLUGIN_OUTPUT_DIRECTORY ${target} LIBRARY_OUTPUT_DIRECTORY)
      string(REPLACE "$<CONFIG>" "%1" PLUGIN_OUTPUT_DIRECTORY ${PLUGIN_OUTPUT_DIRECTORY})
      get_target_property(PLUGIN_IS_BUNDLE ${target}_${format} BUNDLE)
      if(PLUGIN_IS_BUNDLE)
        get_target_property(PLUGIN_EXTENSION ${target}_${format} BUNDLE_EXTENSION)
      else()
        set(PLUGIN_EXTENSION "exe")
      endif()
      set(PLUGIN_PATH "${PLUGIN_OUTPUT_DIRECTORY}/${format}/${PLUGIN_NAME}.${PLUGIN_EXTENSION}")
      cmake_path(NATIVE_PATH PLUGIN_PATH NORMALIZE PLUGIN_PATH)
      set(${targetpath} "${PLUGIN_PATH}" PARENT_SCOPE)
    endif()
  endif()
endfunction(target_get_output_path)

# - Enables the generic code-signing for the target
#
# The function enables the code-signing given specific arguments.
# See target_enable_cjap_codesign
function(target_enable_cjap_generic_codesign target format)
  if(CJAP_CODESIGN_ENABLED AND TARGET ${target}_${format})
    if(TARGET ${CJAP_CODESIGN_PROJECT_NAME}_CodeSign)
      target_get_output_path(${target} ${format} ARTEFACT_PATH)
      if(APPLE)
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "$SIGNATOR \"${ARTEFACT_PATH}\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "if [ $? -ne 0 ]; then\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "  echo \"Signing failed for ${target}_${format}\"\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "  exit 1\n")
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "fi\n")
      elseif(WIN32)
        file(APPEND "${CJAP_CODESIGN_SIGNATOR_ALL_FILE_PATH}" "call ${CJAP_CODESIGN_SIGNATOR_FILE_PATH} \"${ARTEFACT_PATH}\"\n")
      endif()
    else()
      get_target_property(ARTEFACT_FILE ${target}_${format} JUCE_PLUGIN_ARTEFACT_FILE)
      add_custom_command(TARGET ${target}_${format} POST_BUILD COMMAND ${CJAP_CODESIGN_SIGNATOR_FILE_PATH} "${ARTEFACT_FILE_NAT}" VERBATIM)
    endif()
    if(APPLE)
      set_target_properties(${target}_${format} PROPERTIES XCODE_ATTRIBUTE_ENABLE_HARDENED_RUNTIME YES)
      set_target_properties(${target}_${format} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_INJECT_BASE_ENTITLEMENTS "$<$<CONFIG:Debug>:YES>")
    endif()
  endif()
endfunction(target_enable_cjap_generic_codesign)

# - Enables the code-signing for the target
#
# The function enables the code-signing for:
# VST3, AudioUnits, AAX
function(target_enable_cjap_codesign target)
  if(APPLE)
    if(TARGET ${CJAP_CODESIGN_PROJECT_NAME}_CodeSign)
      add_dependencies(${CJAP_CODESIGN_PROJECT_NAME}_CodeSign  ${target}_All)
    endif()
    target_enable_cjap_generic_codesign(${target} "AU")
    target_enable_cjap_generic_codesign(${target} "VST3")
    target_enable_cjap_generic_codesign(${target} "Standalone")
    if(CJAP_CODESIGN_WRAPTOOL_EXE)
      target_enable_cjap_generic_codesign(${target} "AAX")
    endif()
  elseif(WIN32)
    if(TARGET ${CJAP_CODESIGN_PROJECT_NAME}_CodeSign)
      add_dependencies(${CJAP_CODESIGN_PROJECT_NAME}_CodeSign  ${target}_All)
    endif()
    if(CJAP_CODESIGN_WRAPTOOL_EXE)
      target_enable_cjap_generic_codesign(${target} "AAX")
    endif()
  endif()
endfunction(target_enable_cjap_codesign)

